# Generated by Django 5.2.15 on 2026-06-18 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Адрес (slug)')),
                ('type', models.CharField(choices=[('restaurant', 'Ресторан'), ('cafe', 'Кафе'), ('chaikhana', 'Чайхана'), ('fastfood', 'Фастфуд')], default='restaurant', max_length=20, verbose_name='Тип')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Город')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/', verbose_name='Логотип')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание (UZ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('director', 'Директор'), ('administrator', 'Управляющий'), ('manager', 'Менеджер'), ('waiter', 'Официант'), ('kitchen', 'Кухня')], max_length=20, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='restaurants.restaurant', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'constraints': [models.UniqueConstraint(fields=('user', 'restaurant'), name='unique_user_per_restaurant')],
            },
        ),
    ]
