# Generated by Django 5.2.15 on 2026-06-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=60, unique=True, verbose_name='Адрес (slug)'),
        ),
    ]
