# Generated by Django 5.2.15 on 2026-06-18 12:09

import apps.restaurants.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название/номер')),
                ('qr_token', models.CharField(default=apps.restaurants.models.gen_qr_token, editable=False, max_length=32, unique=True, verbose_name='QR-токен')),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Мест')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
