# Generated by Django 5.2.15 on 2026-06-20 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='waiters',
            field=models.ManyToManyField(blank=True, related_name='assigned_tables', to=settings.AUTH_USER_MODEL, verbose_name='Официанты'),
        ),
    ]
