# Generated by Django 5.2.15 on 2026-06-20 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_tablezone_table_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accent', models.CharField(default='#C75B39', max_length=7, verbose_name='Акцент')),
                ('bg', models.CharField(default='#FBF6EE', max_length=7, verbose_name='Фон')),
                ('text', models.CharField(default='#2A2118', max_length=7, verbose_name='Текст')),
                ('card_bg', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Фон карточек')),
                ('font', models.CharField(choices=[('classic', 'Классика'), ('modern', 'Современный'), ('elegant', 'Элегантный'), ('rounded', 'Мягкий')], default='classic', max_length=20, verbose_name='Шрифт')),
                ('card_style', models.CharField(choices=[('list', 'Список с фото'), ('grid', 'Плитка'), ('compact', 'Компактный')], default='list', max_length=10, verbose_name='Стиль карточек')),
                ('radius', models.CharField(choices=[('none', 'Прямые углы'), ('sm', 'Слегка'), ('md', 'Средне'), ('lg', 'Сильно')], default='lg', max_length=6, verbose_name='Скругление')),
                ('show_desc', models.BooleanField(default=True, verbose_name='Показывать описания')),
                ('show_logo', models.BooleanField(default=True, verbose_name='Логотип в шапке')),
                ('header_layout', models.CharField(choices=[('left', 'Слева'), ('center', 'По центру')], default='left', max_length=8, verbose_name='Шапка')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='restaurants/covers/', verbose_name='Обложка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='restaurants.restaurant', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Дизайн меню',
                'verbose_name_plural': 'Дизайн меню',
            },
        ),
    ]
