# Generated by Django 5.2.15 on 2026-06-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_menutheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='session_opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Сессия открыта'),
        ),
    ]
