# Generated by Django 5.2.15 on 2026-06-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurant_registered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menutheme',
            name='card_style',
            field=models.CharField(choices=[('list', 'Список с фото'), ('grid', 'Плитка'), ('compact', 'Компактный'), ('featured', 'Крупные фото')], default='list', max_length=10, verbose_name='Стиль карточек'),
        ),
    ]
