# Generated by Django 5.2.15 on 2026-06-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_menutheme_card_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='session_closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Сессия закрыта'),
        ),
    ]
