# Generated by Django 5.2.15 on 2026-06-18 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0003_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=120, verbose_name='Название (RU)')),
                ('name_uz', models.CharField(blank=True, max_length=120, verbose_name='Название (UZ)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='Название (EN)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.restaurant', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=150, verbose_name='Название (RU)')),
                ('name_uz', models.CharField(blank=True, max_length=150, verbose_name='Название (UZ)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='Название (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание (UZ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('photo', models.ImageField(upload_to='dishes/', verbose_name='Фото')),
                ('weight', models.CharField(blank=True, max_length=40, verbose_name='Вес/объём')),
                ('spiciness', models.PositiveSmallIntegerField(choices=[(0, 'Не острое'), (1, 'Слабо острое'), (2, 'Острое'), (3, 'Очень острое')], default=0, verbose_name='Острота')),
                ('prep_time', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Время (мин)')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DishVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=80, verbose_name='Вариант (RU)')),
                ('name_uz', models.CharField(blank=True, max_length=80, verbose_name='Вариант (UZ)')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='Вариант (EN)')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (сум)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='menu.dish', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Вариант блюда',
                'verbose_name_plural': 'Варианты блюда',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
