# Generated by Django 5.2.15 on 2026-06-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('start', 'Старт'), ('business', 'Бизнес'), ('network', 'Сеть')], default='start', max_length=20, verbose_name='Тариф'),
        ),
    ]
