# Generated by Django 5.2.15 on 2026-06-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_lead_user_is_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='venue_type',
            field=models.CharField(blank=True, choices=[('restaurant', 'Ресторан'), ('cafe', 'Кафе'), ('chaikhana', 'Чайхана'), ('fastfood', 'Фастфуд')], max_length=20, verbose_name='Тип заведения'),
        ),
    ]
