# Generated by Django 5.2.15 on 2026-06-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_lead_venue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_suspended',
            field=models.BooleanField(default=False, help_text='Ручная блокировка доступа независимо от срока.', verbose_name='Подписка приостановлена'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_until',
            field=models.DateField(blank=True, help_text='Пусто — без ограничений. Дата в прошлом — подписка истекла, доступ закрыт.', null=True, verbose_name='Подписка до'),
        ),
    ]
